DROP TABLE IF EXISTS passenger;
DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS flight;
DROP TABLE IF EXISTS airplane;
DROP TABLE IF EXISTS airport;
DROP TABLE IF EXISTS api_key;
DROP TABLE IF EXISTS agency;